### ISSUE TITLE
配置中没有找到相关的配置。 再提个小建议，能否增加一个开关用于配置是否每次修改完都刷新呢？容易找不到刚刚在改的代码。 比如改为每次重新打开一个文件的时候随机一次颜色？

### ISSUE THREAD

**Issue by ZHOUXING1997** [AutoMaintyc/ColorfulBrackets#9]
> 配置中没有找到相关的配置，我不太清楚是指什么配置？

![image](https://github.com/AutoMaintyc/ColorfulBrackets/assets/33240857/800f5053-ebe6-4463-be19-530ba3874e45)
![image](https://github.com/AutoMaintyc/ColorfulBrackets/assets/33240857/a81da2db-d4e3-4f42-8486-7f8536900dd5)

**Comment by ZHOUXING1997** [comment]
![image](https://github.com/AutoMaintyc/ColorfulBrackets/assets/33240857/b9e4c8aa-34a1-42e7-8a66-1222d08a6c46)

简介里面的所指到的配置，是不是在您这一次更新中？

**Comment by AutoMaintyc** [comment]
> > 配置中没有找到相关的配置，我不太清楚是指什么配置？
> 
> ![image](https://private-user-images.githubusercontent.com/33240857/339238804-800f5053-ebe6-4463-be19-530ba3874e45.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyNjA4NTEsIm5iZiI6MTcxODI2MDU1MSwicGF0aCI6Ii8zMzI0MDg1Ny8zMzkyMzg4MDQtODAwZjUwNTMtZWJlNi00NDYzLWJlMTktNTMwYmEzODc0ZTQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEzVDA2MzU1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc5ODNjNjdmODJkMDZjYjg2MWU5YjAwMDFmN2RhYWQwMDgwNmZjMDhmZGY0YjJhNzFiOTVkMzFjMWNhYjI4MDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.44Valgd3F_6UTVr8koLBvjsA8BixcohFujP17iNgbo0) ![image](https://private-user-images.githubusercontent.com/33240857/339238888-a81da2db-d4e3-4f42-8486-7f8536900dd5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyNjA4NTEsIm5iZiI6MTcxODI2MDU1MSwicGF0aCI6Ii8zMzI0MDg1Ny8zMzkyMzg4ODgtYTgxZGEyZGItZDRlMy00ZjQyLTg0ODYtN2Y4NTM2OTAwZGQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEzVDA2MzU1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI1ZGQzZGMxZWNlZjRiMzg2MmIyOTYyOWZkMGUxNDYyNjcxYWNhYTk2Zjg4OTk2NzVkMWE1Zjk1YWY1MDE4YWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DZ4y7MOgOs790fEDt1iixwhetYgu4z2Du8HnTsBsCN0)

Jetbrains把配置更上去了，但最新的包没有更新出去，提示我两个工作日内会更新

**Comment by AutoMaintyc** [comment]
> ![image](https://private-user-images.githubusercontent.com/33240857/339239781-b9e4c8aa-34a1-42e7-8a66-1222d08a6c46.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyNjA5NTIsIm5iZiI6MTcxODI2MDY1MiwicGF0aCI6Ii8zMzI0MDg1Ny8zMzkyMzk3ODEtYjllNGM4YWEtMzRhMS00MmU3LThhNjYtMTIyMmQwOGE2YzQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEzVDA2MzczMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM4YjFjNzgyZDVkZTRiOWVkODM4OTA0YWI1NWE2YzYyNzI2MWMwZmY0MDRkNzcwNjI2ZTBmYzZkMmFlNzI4N2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yQlpNOge56otEaJu5_vYjU14XnPjI7Du9nh41lNSh3Q)
> 
> 简介里面的所指到的配置，是不是在您这一次更新中？

是的，但jetbrains说要等两个工作日

**Comment by ZHOUXING1997** [comment]
那我没问题了，我就是没找到这个配置。😂
